name: Learning GitHub Script

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Issue にコメントを追加
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 You've created this issue comment using GitHub Script!!!"
            });

            // Project の Column にカードを追加
            await github.projects.createCard({
              column_id: process.env.COLUMN_ID,
              content_id: context.payload.issue.id,
              content_type: "Issue"
            });
        env:
          COLUMN_ID: ${{ secrets.COLUMN_ID }}
